# Generated by Django 4.2 on 2025-07-25 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comments_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.TimeField(),
        ),
        migrations.AlterModelTable(
            name='blog',
            table='Blogs',
        ),
    ]
